/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts;

import static java.lang.String.format;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.text.DateFormat;
import javax.swing.JOptionPane;
import java.math.BigInteger;
import java.lang.Object;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Mokleters
 */
public class formRental extends javax.swing.JFrame {

    /**
     * Creates new form formRental
     */
    public formRental() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNopol = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNoStruk = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Balik = new com.toedter.calendar.JDateChooser();
        Pinjam = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnHarga = new javax.swing.JButton();
        txtHarga = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnRefresh = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRental = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 51, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 1, 36)); // NOI18N
        jLabel1.setText("Rental Motor Bli Nyoman");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 450, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1190, 90);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 90, 1190, 10);

        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Tgl. Kembali");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 220, 90, 30);

        txtNama.setFont(new java.awt.Font("Amphion", 0, 14)); // NOI18N
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        jPanel2.add(txtNama);
        txtNama.setBounds(90, 60, 320, 30);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Nama");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 60, 50, 30);

        txtNopol.setFont(new java.awt.Font("Amphion", 0, 14)); // NOI18N
        jPanel2.add(txtNopol);
        txtNopol.setBounds(90, 140, 320, 30);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Alamat");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 100, 60, 30);

        txtAlamat.setFont(new java.awt.Font("Amphion", 0, 14)); // NOI18N
        jPanel2.add(txtAlamat);
        txtAlamat.setBounds(90, 100, 320, 30);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setText("No. Struk");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 20, 70, 30);

        txtNoStruk.setFont(new java.awt.Font("Amphion", 0, 14)); // NOI18N
        jPanel2.add(txtNoStruk);
        txtNoStruk.setBounds(90, 20, 320, 30);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setText("NoPol");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 140, 70, 30);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Tgl. Pinjam");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 180, 80, 30);
        jPanel2.add(Balik);
        Balik.setBounds(100, 220, 310, 30);

        Pinjam.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                PinjamPropertyChange(evt);
            }
        });
        jPanel2.add(Pinjam);
        Pinjam.setBounds(100, 180, 310, 30);

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel9.setText("Harga rental:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(90, 340, 190, 50);

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel10.setText("Rp");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(40, 380, 40, 50);

        btnHarga.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        btnHarga.setText("Hitung Harga");
        btnHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHargaActionPerformed(evt);
            }
        });
        jPanel2.add(btnHarga);
        btnHarga.setBounds(150, 270, 200, 40);

        txtHarga.setEditable(false);
        txtHarga.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jPanel2.add(txtHarga);
        txtHarga.setBounds(90, 390, 260, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 90, 430, 500);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(430, 90, 10, 500);

        btnRefresh.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefresh);
        btnRefresh.setBounds(440, 100, 150, 80);

        btnSave.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btnSave);
        btnSave.setBounds(630, 110, 110, 30);

        btnPrint.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrint);
        btnPrint.setBounds(630, 150, 110, 30);

        btnClear.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear);
        btnClear.setBounds(880, 150, 110, 30);

        btnDel.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        getContentPane().add(btnDel);
        btnDel.setBounds(1010, 150, 110, 30);

        tblRental.setBackground(new java.awt.Color(0, 255, 255));
        tblRental.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblRental.setFont(new java.awt.Font("Eras Medium ITC", 0, 14)); // NOI18N
        tblRental.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No. Struk", "Nama Peminjam", "Alamat", "NoPol", "Tgl. Pinjam", "Tgl. Kembali", "Harga"
            }
        ));
        tblRental.setCellSelectionEnabled(true);
        tblRental.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRentalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRental);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(430, 190, 760, 402);

        btnEdit.setFont(new java.awt.Font("News701 BT", 0, 14)); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit);
        btnEdit.setBounds(750, 130, 120, 30);

        setBounds(0, 0, 1208, 627);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        selectData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        MessageFormat header = new MessageFormat("Rental Motor Bli Nyoman");
        MessageFormat footer = new MessageFormat("Halaman {0,number,integer}");
        try {
            tblRental.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtNoStruk.setText("");
        txtNama.setText("");
        txtAlamat.setText("");
        txtNopol.setText("");
        Pinjam.setDate(null);
        Balik.setDate(null);
        txtHarga.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        int baris = tblRental.getSelectedRow();
        if (baris != -1) {
            String nostruk = tblRental.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM t_peminjam WHERE nostruk='"+nostruk+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris data terlebih dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String pinjam = dateFormat.format(Pinjam.getDate());
        String balik = dateFormat.format(Balik.getDate());
        if(txtNoStruk.getText().equals("") || txtNama.getText().equals("") || txtAlamat.getText().equals("") || txtNopol.getText().equals("") ||
                pinjam.equals("") || balik.equals("")){
            JOptionPane.showMessageDialog(this, "Harap lengkapi data", "Error", JOptionPane.WARNING_MESSAGE);
        } else if (txtHarga.equals("")){
            JOptionPane.showMessageDialog(this, "Harga belum dihitung", "Peringatan", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
            String SQL = "INSERT INTO t_peminjam VALUES ('"+txtNoStruk.getText()+"', '"+txtNama.getText()
                    +"', '"+txtAlamat.getText()+"', '"+txtNopol.getText()+"', '"+pinjam+"', '"+balik+"', '"+txtHarga.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if(status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }
            selectData();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHargaActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String pinjam = dateFormat.format(Pinjam.getDate());
        String balik = dateFormat.format(Balik.getDate());
        
        try {
            Date pinjam1 = dateFormat.parse(pinjam);
            Date balik1 = dateFormat.parse(balik);

            long d1= pinjam1.getTime();
            long d2= balik1.getTime();
            
            long diff = d2 - d1;
            
            Long diffDays = (diff / (24 * 60 * 60 * 1000)) * 20000;
            txtHarga.setText(Long.toString(diffDays));
            
        } catch (Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnHargaActionPerformed

    private void PinjamPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_PinjamPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_PinjamPropertyChange

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String pinjam = dateFormat.format(Pinjam.getDate());
        String balik = dateFormat.format(Balik.getDate());
        if(txtNoStruk.getText().equals("") || txtNama.getText().equals("") || txtAlamat.getText().equals("") || txtNopol.getText().equals("") ||
                pinjam.equals("") || balik.equals("")){
            JOptionPane.showMessageDialog(this, "Harap lengkapi data", "Error", JOptionPane.WARNING_MESSAGE);
        } else if (txtHarga.equals("")){
            JOptionPane.showMessageDialog(this, "Harga belum dihitung", "Peringatan", JOptionPane.INFORMATION_MESSAGE);
        }
        else {
        String SQL = "UPDATE t_peminjam SET "
                + "nostruk='"+txtNoStruk.getText()+"',"
                + "nama='"+txtNama.getText()+"',"
                + "alamat='"+txtAlamat.getText()+"',"
                + "nopol='"+txtNopol.getText()+"',"
                + "pinjam='"+pinjam+"',"
                + "balik='"+balik+"',"
                + "harga='"+txtHarga.getText()+"'";
        int status = KoneksiDB.execute(SQL);
        if(status == 0){
            JOptionPane.showMessageDialog(this, "Data berhasil di-update", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            selectData();
        } else {
            JOptionPane.showMessageDialog(this, "Data gagal di-update", "Gagal", JOptionPane.WARNING_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void tblRentalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRentalMouseClicked
        int baris = tblRental.getSelectedRow();
        if (baris != -1) {
            txtNoStruk.setText(tblRental.getValueAt(baris, 0).toString());
            txtNama.setText(tblRental.getValueAt(baris, 1).toString());
            txtAlamat.setText(tblRental.getValueAt(baris, 2).toString());
            txtNopol.setText(tblRental.getValueAt(baris, 3).toString());
                    SimpleDateFormat date = new SimpleDateFormat("yyyy/MM/dd");
                    Date dateFormat1 = null;
                    Date dateFormat2 = null;
                    try {
                        dateFormat1 = date.parse(tblRental.getValueAt(baris, 4).toString());
                    } catch (ParseException ex) {
                        Logger.getLogger(formRental.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    try {
                        dateFormat2 = date.parse(tblRental.getValueAt(baris, 5).toString());
                    } catch (ParseException ex) {
                        Logger.getLogger(formRental.class.getName()).log(Level.SEVERE, null, ex);
                    }
            Pinjam.setDate(dateFormat1);
            Balik.setDate(dateFormat2);
            txtHarga.setText(tblRental.getValueAt(baris, 6).toString());
        }
    }//GEN-LAST:event_tblRentalMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formRental().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Balik;
    private com.toedter.calendar.JDateChooser Pinjam;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHarga;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblRental;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNoStruk;
    private javax.swing.JTextField txtNopol;
    // End of variables declaration//GEN-END:variables

    public void selectData() {
        String kolom[] = {"No. Struk","Nama Peminjam","Alamat","NoPol","Tgl. Pinjam","Tgl. Kembali","Harga"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM t_peminjam";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()) {
                String nostruk = rs.getString(1);
                String nama = rs.getString(2);
                String alamat = rs.getString(3);
                String nopol = rs.getString(4);
                String pinjam = rs.getString(5);
                String balik = rs.getString(6);
                String harga = rs.getString(7);
                String data[] = {nostruk,nama,alamat,nopol,pinjam,balik,harga};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(formRental.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblRental.setModel(dtm);
    }

}
